Lesson7
dosim88/react pull request #7
Opened 2017-07-30 20:40 UTC by dosim88

2017-07-30 21:04 UTC, index01d requested changes
Оставил некоторые замечания, предлагаю выделить LikeContainer и устранить второй аргумент actionCreator'a like'a. Знать про все посты ему явно ни к чему

2017-07-30 21:04 UTC, index01d commented on src/actions/post.js
> +      endpoint: posts(id),
роут-хелпер здесь использовать не очень уместно, тк урл на апи может совсем даже не совпадать с нашими внутренними в апке

2017-07-30 21:04 UTC, index01d commented on src/components/containers/postsContainer.js
>  import { connect } from 'react-redux';
файлы с контейнерными компонентами лучше именовать с большой буквы (негласная конвенция для компонентов в целом)

2017-07-30 21:04 UTC, index01d commented on src/components/ui/pagination.js
>  import _ from 'lodash';
лучше импортировать конкретные функции аля `import { map } from 'lodash'`

2017-07-30 21:04 UTC, index01d commented on src/components/views/blogList.jsx
> +        <Pagination items={posts} currentPage={currentPage} changePage={changePage}/>
не похоже, чтобы items там был нужен. Вроде там достаточно count

2017-07-30 21:04 UTC, index01d commented on src/components/views/blogList.jsx
> +        <Pagination items={posts} currentPage={currentPage} changePage={changePage}/>
также лучше сделать PaginationContainer и спрятать туда подсчет этих свойств.

2017-07-30 21:04 UTC, index01d commented on src/components/views/blogList.jsx
>                handleLike={ () => handleLike(post.id, posts) }
можно сделать LikeContainer, чтобы не таскать этот коллбэк по иерархии. Кстати, второй аргумент в handleLike не нужен, достаточно id

2017-07-30 21:05 UTC, index01d commented on src/components/views/blogList.jsx
>                handleLike={ () => handleLike(post.id, posts) }
кстати postsOnPage мне кажется избыточным названием и свойством, предлагаю ложить нужный состав в posts и тут использовать

2017-08-02 17:50 UTC, dosim88 commented
Исправил все замечания кроме одного.
Не добавил LikeContainer. Пока не пойму как это сделать красиво.

Сложности такие:
1. У меня 2 actionCreator'a для like'a, отдельно для Posts и Post.
По идее это правильно, т.к. состояние разделенно на Posts и Post.
Прийдется определять какой именно actionCreator вызывать.
2. Нужно в LikeContainer как-то передавать id поста. Немного погуглил, но не понял как это можно грамотно проделать с контейнерным компонентом Redux.
Наверняка подобный "велосипед" изобретется, но врядли пройдет контроль качества )

Как тут лучше поступить?

2017-08-02 19:03 UTC, index01d commented
я имею ввиду примерно следующую схему (на примере кода другого ученика):

В LikeContainer реализовать redux-container:

```
import { get, find, flowRight } from 'lodash';

import Like from 'components/ui/Like';
import { addLike } from 'actions/Like';

...
const stateToProps = (state, ownProps) => ({
  amount: get(
    find(state.posts.items, { id: ownProps.itemId }), 
    'likes', 
    get(state, 'post.item.likes', 0)
  )
});

const actionsToProps = (dispatch, ownProps) => (
  addLike: () => dispatch(addLike(ownProps.itemId))
);

export default connect(stateToProps, actionsToProps)(Like);
```

Презентационный компонент станет таким

```
import React from 'react';
import Button from 'react-mdl/lib/Button';


const Likes = ({addLike, amount}) =>{

    return(
        <Button onClick={()=> addLike()}
             style={{border: '1px solid green',
             width: 'auto',
             cursor: 'pointer'}}>
            {`likes: ${amount}`}
        </Button>
    )
};


Like.propTypes = {
    amount: React.PropTypes.number.isRequired,
    addLike: React.PropTypes.func.isRequired
};

export default Like;
```

В BlogItem использовать его следующим образом

```
import LikeContainer from 'containers/LikeContainer';
...
<LikeContainer itemId={item.id} /> // здесь разумеется рендерить с условием, только когда item.id уже есть
```

2017-08-02 19:03 UTC, index01d commented
ты можешь обработать один и тот же action в нескольких редьюсерах (Posts и Post). (это ответ про action и разные состояния)

2017-08-05 12:18 UTC, index01d approved these changes

2017-08-05 19:40 UTC, merged